sudo: required
services:
- docker
env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- docker run --name mongo -p 27017:27017 -d mongo:3.2 
- docker run --name redis -p 6379:6379 -d redis:3.0 
- sleep 30s
- docker exec $(docker ps -aqf "name=mongo") mongo _GLOBAL --eval "db.getCollection('_Settings').insertOne({secureKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',clusterKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',myURL:'http://localhost:4730'});"
- docker run --name cloudboost -p 4730:4730 -it --link redis:redis --link mongo:mongo -d cloudboost/cloudboost:latest
- sleep 30s
install:
- npm install
- docker build -t cloudboost/user-service:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/user-service:latest .
- docker run --name user-service -e  MANDRILL=$MANDRILL -e  MIXPANEL_TOKEN=$MIXPANEL_TOKEN -e  MAILCHIMP_API_KEY=$MAILCHIMP_API_KEY -e  LOG_TOKEN=$LOG_TOKEN -e  MAILGUN_API_KEY=$MAILGUN_API_KEY -e  MAIL_GUN_DOMAIN=$MAIL_GUN_DOMAIN -e ADMIN_EMAIL=$ADMIN_EMAIL -e HEROKU_USERNAME=$HEROKU_USERNAME -e HEROKU_PASSWORD=$HEROKU_PASSWORD -e HEROKU_SALT=$HEROKU_SALT -p 3000:3000 -it --link cloudboost:api --link mongo:mongo -d cloudboost/user-service:2.0.$TRAVIS_BUILD_NUMBER 
- sleep 30s
- docker exec user-service env
after_success:
- echo "OK"
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=2.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITLOGIN@github.com/CloudBoost/user-service --tags
  - ls -R
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "README.md"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
after_deploy:
# Docker Deploy.
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL;
  docker push cloudboost/user-service:2.0.$TRAVIS_BUILD_NUMBER;
  docker push cloudboost/user-service:latest;
  fi
branches:
  except:
    - /^*-v[0-9]/
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW